### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Love-Studyyy** [llz-lian/bysjchange_polygon_RNN#2]
hello, can I ask you a question?
I always meet the problem:
it trouble me a lot

Loading completed!
Traceback (most recent call last):
  File "d:/bysjchange_polygon_RNN-main/train.py", line 110, in <module>
    train(config, config['pretrained'])
  File "d:/bysjchange_polygon_RNN-main/train.py", line 52, in train
    for step, data in enumerate(Dataloader):#4->
  File "D:\Segment\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "D:\Segment\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 403, in _next_data       
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Segment\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\Segment\envs\pytorch\lib\site-packages\torch\utils\data\_utils\collate.py", line 86, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>

How can I solve the None Type Error?
Thank you and best wishes

**Comment by llz-lian** [comment]
[dataset](https://www.cityscapes-dataset.com)
python generate_data.py --data train/val/test

**Comment by Love-Studyyy** [comment]
Thank you! But it doesn't work. 
python generate_data.py --data train/val/test:
count 0
max_count 0

can you show me how to set the path?

my structure:
>__pychache__
>.vscode
>backbone
>datas
>img>test
         >train
         >val
>label>test
         >train
         >val
>nets
>new_img\test
>new_label\test
>utils
config_tools.py
default_config.yaml
fpstest.py
generate_data.py
test.py
train.py
validate.py

Thank you very much!

**Comment by Love-Studyyy** [comment]
Thank you! But it doesn't work. 
python generate_data.py --data train/val/test:
count 0
max_count 0

can you show me how to set the path?

my structure:
>__pychache__
>.vscode
>backbone
>datas
>img\test  \ train  \val
>label\test  \train  \val
>nets
>new_img\test
>new_label\test
>utils
config_tools.py
default_config.yaml
fpstest.py
generate_data.py
test.py
train.py
validate.py

**Comment by Love-Studyyy** [comment]
Thank you very much!
